databases:
  - name: oimyuaws
    plan: free
    databaseName: oimyuaws
    user: spibceyq

services:
  - type: web
    plan: free
    name: saleor
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn saleor.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_CONNECTION_STRING
        fromDatabase:
          name: oimyuaws
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4